/**
 * Generated bundle index. Do not edit.
 */
export * from './public_api';
export { getBaseHref as ɵbm } from './lib/getBaseHref';
export { ConsoleLoggerService as ɵbn } from './lib/services/logging/console-logger.service';
export { LoggerService as ɵd } from './lib/services/logging/logger.service';
export { ClientFileSystemService as ɵc } from './lib/services/pure/client-filesystem.service';
export { IconUrlResolverService as ɵe } from './lib/services/pure/icon-url-resolver.service';
export { NotificationService as ɵg } from './lib/services/pure/notification.service';
export { OptimisticFilesystemService as ɵf } from './lib/services/pure/optimistic-filesystem.service';
export { FilemanagerStatusService as ɵh } from './lib/services/state/status.service';
export { AppBulkActionsComponent as ɵj } from './lib/ui/actions-toolbars/bulk-actions.component';
export { AppMainActionsComponent as ɵk } from './lib/ui/actions-toolbars/main-actions.component';
export { AppBreadCrumbsComponent as ɵi } from './lib/ui/bread-crumbs/bread-crumbs.component';
export { BaseDialogComponent as ɵbc } from './lib/ui/dialogs/base-dialog.component';
export { AppBtnsCancelOkComponent as ɵbl } from './lib/ui/dialogs/btns-cancel-ok.component';
export { AppDialogConfirmationComponent as ɵbk } from './lib/ui/dialogs/dialog-confirmation.component';
export { AppDialogCopyComponent as ɵbh } from './lib/ui/dialogs/dialog-copy-or-move.component';
export { AppDialogMyDetailsComponent as ɵbj } from './lib/ui/dialogs/dialog-my-details.components';
export { AppDialogNewFolderComponent as ɵbe } from './lib/ui/dialogs/dialog-new-folder.component';
export { AppDialogPermissionsSetComponent as ɵbf } from './lib/ui/dialogs/dialog-permissions-set.component';
export { AppDialogPermissionsSetObjectComponent as ɵbg } from './lib/ui/dialogs/dialog-permissions-setobject.component';
export { AppDialogRenameComponent as ɵbd } from './lib/ui/dialogs/dialog-rename.component';
export { AppDialogUploadFilesComponent as ɵbi } from './lib/ui/dialogs/dialog-upload.component';
export { NgxFilemanagerClientDialogsModule as ɵw } from './lib/ui/dialogs/dialogs.module';
export { FileDetailsComponent as ɵl } from './lib/ui/file-details/file-details.component';
export { FileSizeModule as ɵm } from './lib/ui/file-size/file-size.module';
export { FileSizePipe as ɵn } from './lib/ui/file-size/file-size.pipe';
export { AppActionsMiniBrowserComponent as ɵz } from './lib/ui/file-table-mini/actions-mini-browser.component';
export { AppFileTableMiniFolderBrowserComponent as ɵy } from './lib/ui/file-table-mini/file-table-mini-folder-browser.component';
export { FileTableMiniModule as ɵx } from './lib/ui/file-table-mini/file-table-mini.module';
export { CardFileComponent as ɵr } from './lib/ui/file-table/card-file.component';
export { CardFolderComponent as ɵq } from './lib/ui/file-table/card-folder.component';
export { AppFileTableComponent as ɵp } from './lib/ui/file-table/file-table.component';
export { AppFileTableModule as ɵo } from './lib/ui/file-table/file-table.module';
export { FormFileFirebaseModule as ɵs } from './lib/ui/file-upload/file-upload.module';
export { FormBase as ɵu } from './lib/ui/file-upload/form-file-firebase/form-base-class';
export { FormFileFirebaseComponent as ɵt } from './lib/ui/file-upload/form-file-firebase/form-file-firebase.component';
export { FormFileUploadedFileListComponent as ɵv } from './lib/ui/file-upload/form-file-firebase/form-file-uploader-list.component';
export { ActionHandlersService as ɵb } from './lib/ui/main-file-manager/action-handlers.service';
export { LibMainFileManagerComponent as ɵa } from './lib/ui/main-file-manager/main-file-manager.component';
export { AppControlTagMultipleComponent as ɵbb } from './lib/ui/tags-control/tags-control.component';
export { TagsControlModule as ɵba } from './lib/ui/tags-control/tags-control.module';
